### ISSUE TITLE
Assessment unit overlap

### ISSUE THREAD

**Issue by HjalteParner** [ices-tools-dev/COMPEAT#1]
The assessment units size and shape are defined by the contracting parties using guidelines within the OSPAR Common Procedure.

The OSPAR Eutrophication Assessment Tool assume that the assessment units cannot overlap one another and as such one station (defined by a given position, date and time) should only be within one assessment unit.

However looking at the assessment units currently in context (Sweden, Germany and Netherlands) its apparent that some assessment units overlap both within a country and among countries. This issue will lead to duplicates and bias in the indicator and assessment results as it stands.

How should this issue be addressed?

Below a table with the current overlaps:

- Sweden and Netherlands assessment units overlaps themselves.
- Germany and Netherlands assessment units overlaps each other.  

| ID | Code    | Description        | ID | Code    | Description                                          |
|----|---------|--------------------|----|---------|------------------------------------------------------|
| 30 | NLD-007 | Dogger Bank        | 1  | DEU-001 | OFFO                                                 |
| 28 | NLD-006 | Oyster Grounds     | 2  | DEU-002 | OFFI                                                 |
| 30 | NLD-007 | Dogger Bank        | 2  | DEU-002 | OFFI                                                 |
| 28 | NLD-006 | Oyster Grounds     | 4  | DEU-004 | OCEF                                                 |
| 29 | NLD-001 | Coastal waters     | 4  | DEU-004 | OCEF                                                 |
| 27 | NLD-004 | Ems-Dollard        | 6  | DEU-006 | ICEF                                                 |
| 29 | NLD-001 | Coastal waters     | 6  | DEU-006 | ICEF                                                 |
| 27 | NLD-004 | Ems-Dollard        | 8  | DEU-008 | EF12                                                 |
| 27 | NLD-004 | Ems-Dollard        | 10 | DEU-010 | EF34                                                 |
| 29 | NLD-001 | Coastal waters     | 10 | DEU-010 | EF34                                                 |
| 27 | NLD-004 | Ems-Dollard        | 14 | DEU-014 | Ems                                                  |
| 22 | SWE-008 | Skagerrak open sea | 17 | SWE-004 | 3. Outer coastal waters of the west coast. Skagerrak |
| 22 | SWE-008 | Skagerrak open sea | 20 | SWE-005 | 4. Outer coastal waters of the west coast. Kattegat  |
| 23 | SWE-009 | Kattegat open sea  | 22 | SWE-008 | Skagerrak open sea                                   |
| 28 | NLD-006 | Oyster Grounds     | 24 | NLD-005 | Southern Bight                                       |
| 29 | NLD-001 | Coastal waters     | 24 | NLD-005 | Southern Bight                                       |
| 27 | NLD-004 | Ems-Dollard        | 25 | NLD-002 | Wadden Sea                                           |
| 29 | NLD-001 | Coastal waters     | 25 | NLD-002 | Wadden Sea                                           |
| 29 | NLD-001 | Coastal waters     | 27 | NLD-004 | Ems-Dollard                                          |
| 29 | NLD-001 | Coastal waters     | 28 | NLD-006 | Oyster Grounds                                       |

**Comment by philipaxe** [comment]
I'm a bit surprised about this, at least for the Swedish regions. The assessment/reporting units should be adjacent to one another, but not overlapping.

**Comment by HjalteParner** [comment]
The Swedish assessment units have been resubmitted, updated from 9 to 11 units with no overlaps. The Dutch and German assessment units in the table above are still to be solved!

**Comment by HjalteParner** [comment]
The Dutch assessment units have been resubmitted, modifying some of the units. However there are still overlaps both internally and externally with regards to the German assessment units.

**Comment by HjalteParner** [comment]
Previous assessment units have been abandoned so this issue is not relevant anymore
