### ISSUE TITLE
Indicator calculation differences

### ISSUE THREAD

**Issue by HjalteParner** [ices-tools-dev/COMPEAT#3]
Indicators are defined by the contracting parties according to the guidelines within the OSPAR Common Procedure.

However the same indicator is calculated differently by different countries and can differ in which months and depth to include and how to do the actual metric.

It would make more sense if the same indicator depends on assessment unit instead country e.g. the assessment units geographical position and characteristic.

**Comment by philipaxe** [comment]
Seems reasonable.

**Comment by HjalteParner** [comment]
We are now using common assessment units where indicator threshold, season and confidence criteria can be specified.
