### ISSUE TITLE
Reference Salinity for Salinity normalization

### ISSUE THREAD

**Issue by HjalteParner** [ices-tools-dev/COMPEAT#6]
Currently the reference salinity for salinity normalization is the mean salinity for the assessment area in question. It need to be corrected to a given salinity by contracting parties related to the assessment threshold.

**Comment by philipaxe** [comment]
We can let you have the reference salinities (when appropriate) for our COMP3 assessment. I've uploaded them extracted from Karin W's report. IIRC, chlorophyll/salinity has a bell-shape in the Kattegat and Skagerrak so we don't normalise it
[SE_COMP3_tables.pdf](https://github.com/ices-tools-dev/COMPEAT/files/2888293/SE_COMP3_tables.pdf)
.

**Comment by philipaxe** [comment]
Whoops - I shouldn't have clicked "close"....
